language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t rintjema/docker-kubernetes -f frontend/Dockerfile.dev .
    
script:
    - docker run -e CI=true rintjema/docker-kubernetes npm run test
      